serial:
  port: "/dev/ttyUSB0"
  baudrate: 115200
  stopbits: 1
  databits: 8
  parity: "none"

frame:
  head: 0xFF
  mode: 0x00
  byte1: 0x00
  byte2: 0x00
  byte3: 0x00
  byte4: 0x00
  byte5: 0x00
  byte6: 0x00
  byte7: 0x00
  tail: 0xFE

mode:
  QRmode: 0x01
  Colormode: 0x02
  Circlemode: 0x03

cam_QRCode: 0
cam_Det: 2

debug_flag: 0
send_latecy_ms: 50

Material_Thresholds:
  lower_blue_contour: [100, 43, 46]
  upper_blue_contour: [124, 255, 255]
  lower_green_contour: [40, 92, 46]
  upper_green_contour: [90, 255, 255]
  lower_red_1_contour: [ 0, 83, 46]
  upper_red_1_contour: [ 24, 255, 255]

Landmark_Thresholds:
  lower_blue_circle: [81, 61, 41]
  upper_blue_circle: [122, 255, 255]
  lower_green_circle: [27, 34, 46]
  upper_green_circle: [58, 255, 255]
  lower_red_1_circle: [0, 126, 0]
  upper_red_1_circle: [20, 255, 255]
  lower_red_2_circle: [161, 42, 0]
  upper_red_2_circle: [179, 255, 255]

Color:
  blue: 0x03
  green: 0x02
  red: 0x01

min_perimeter_threshold: 1000.0

min_radius: 60
Vision_Mode: True
